// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRJ5YVipFhnEYwL1dF211LU8ON0-sFL68',
    appId: '1:840510625229:web:c4686ffc08ddbfcc632084',
    messagingSenderId: '840510625229',
    projectId: 'investigation-assistant',
    authDomain: 'investigation-assistant.firebaseapp.com',
    storageBucket: 'investigation-assistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6xhmVQWzuMnEFKR4fXpMoL3Eft5x2ECs',
    appId: '1:840510625229:android:c0569ba67b58f291632084',
    messagingSenderId: '840510625229',
    projectId: 'investigation-assistant',
    storageBucket: 'investigation-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgpEGQIavC5II4o0EqYxD3sYxPS41D4s',
    appId: '1:840510625229:ios:d7c4e0e4e14db0ae632084',
    messagingSenderId: '840510625229',
    projectId: 'investigation-assistant',
    storageBucket: 'investigation-assistant.firebasestorage.app',
    iosBundleId: 'com.example.investigationAssistantAppFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgpEGQIavC5II4o0EqYxD3sYxPS41D4s',
    appId: '1:840510625229:ios:d7c4e0e4e14db0ae632084',
    messagingSenderId: '840510625229',
    projectId: 'investigation-assistant',
    storageBucket: 'investigation-assistant.firebasestorage.app',
    iosBundleId: 'com.example.investigationAssistantAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRJ5YVipFhnEYwL1dF211LU8ON0-sFL68',
    appId: '1:840510625229:web:7435ee63c4450b6a632084',
    messagingSenderId: '840510625229',
    projectId: 'investigation-assistant',
    authDomain: 'investigation-assistant.firebaseapp.com',
    storageBucket: 'investigation-assistant.firebasestorage.app',
  );
}
